import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";
import MainContainer from "@/app/components/MainContainer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["500", "400", "300", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Spotify-Web Player: Music for every one",
  description: "Generated by Huu Nghia",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <MainContainer>{children}</MainContainer>
      </body>
    </html>
  );
}
